version: 2.1

orbs:
  sonar: hubci/sonar@1.0.0
  cimg: circleci/cimg@dev:2793703a17dc27c436f53d6310a7e4b44f359f74

workflows:
  main:
    jobs:
      - cimg/gen-dockerfiles
      - cimg/build-and-deploy:
          name: "Push to Staging"
          publish-branch: test
          docker-namespace: ccitest
          docker-repository: go
          context: cimg-publishing
          requires:
            - cimg/gen-dockerfiles
