version: 2.1

orbs:
  sonar: hubci/sonar@1.0.0
  cimg: circleci/cimg@dev:f5328e5804113593b45c0b90282ebe6bc1a87335

workflows:
  main:
    jobs:
      - cimg/gen-dockerfiles
      - cimg/build-and-deploy:
          name: "Push to Staging"
          publish-branch: test
          docker-namespace: ccitest
          docker-repository: testing
          context: cimg-publishing
          requires:
            - cimg/gen-dockerfiles
